#!/usr/bin/bash

T_MAX=500
LABEL=1
ITR=040000
EXP_NAME="tiny_cond${ITR}_wiener_t${T_MAX}"
IMG_DIR="results/image/tiny_sample_cond${ITR}_wiener_label0_run0"
# EXP_NAME="tiny_cond${ITR}_gaussian_t${T_MAX}"
# IMG_DIR="results/image/tiny_sample_cond${ITR}_gaussian_label0_run0"
# EXP_NAME="tiny_cond${ITR}_t${T_MAX}"
# IMG_DIR="results/image/tiny_sample_cond${ITR}_label0_run0"
# EXP_NAME="test_resample_dir"
# IMG_DIR="results/test/test_resample_dir"
I_RUN=0
SAMPLE_FLAGS="--batch_size 1 --num_samples 1 --t_max $T_MAX --save_steps 10 --make_gif False --i_run $I_RUN --img_dir $IMG_DIR --label ${LABEL}"


# 64x64
MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --dropout 0.1 --image_size 64 --learn_sigma True --noise_schedule cosine --num_channels 192 --num_head_channels 64 --num_res_blocks 3 --resblock_updown True --use_new_attention_order True --use_fp16 True --use_scale_shift_norm True"
python scripts/image_resample_dir.py $MODEL_FLAGS --exp_name $EXP_NAME --model_path models/64x64_diffusion.pt $SAMPLE_FLAGS 

# MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --dropout 0.1 --image_size 64 --learn_sigma True --noise_schedule cosine --num_channels 192 --num_head_channels 64 --num_res_blocks 3 --resblock_updown True --use_new_attention_order True --use_fp16 True --use_scale_shift_norm True"
# python scripts/image_resample.py $MODEL_FLAGS --exp_name $EXP_NAME --model_path models/64x64_diffusion.pt $SAMPLE_FLAGS 


# 256x256 (unconditional)
# MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond False --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
# python scripts/image_resample.py $MODEL_FLAGS --exp_name $EXP_NAME --model_path models/256x256_diffusion_uncond.pt $SAMPLE_FLAGS 

# 128x128
# MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --image_size 128 --learn_sigma True --noise_schedule linear --num_channels 256 --num_heads 4 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
# python scripts/classifier_sample.py $MODEL_FLAGS --classifier_scale 0.5 --classifier_path models/128x128_classifier.pt --model_path models/128x128_diffusion.pt $SAMPLE_FLAGS
