#!/usr/bin/bash

T_MAX=500
# LABEL=817
# EXP_NAME="trans_404to817_t${T_MAX}"
# IMG_PATH="results/image/tcfg64_label404_run0/tcfg64_label404_0.png"
LABEL=817
EXP_NAME="test_trans_404_817_t${T_MAX}_uncond"
IMG_PATH="results/image/tcfg64_label817_run0/tcfg64_label817_191.png"
I_RUN=2
# SAMPLE_FLAGS="--batch_size 1 --num_samples 1 --t_max $T_MAX --save_steps 10 --make_gif True --i_run $I_RUN --img_path $IMG_PATH --label ${LABEL}"
SAMPLE_FLAGS="--batch_size 1 --num_samples 1 --t_max $T_MAX --save_steps 10 --make_gif True --i_run $I_RUN --img_path $IMG_PATH"


# 64x64
MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --dropout 0.1 --image_size 64 --learn_sigma True --noise_schedule cosine --num_channels 192 --num_head_channels 64 --num_res_blocks 3 --resblock_updown True --use_new_attention_order True --use_fp16 True --use_scale_shift_norm True"
python scripts/image_resample.py $MODEL_FLAGS --exp_name $EXP_NAME --model_path models/64x64_diffusion.pt $SAMPLE_FLAGS 

# MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --dropout 0.1 --image_size 64 --learn_sigma True --noise_schedule cosine --num_channels 192 --num_head_channels 64 --num_res_blocks 3 --resblock_updown True --use_new_attention_order True --use_fp16 True --use_scale_shift_norm True"
# python scripts/image_resample.py $MODEL_FLAGS --exp_name $EXP_NAME --model_path models/64x64_diffusion.pt $SAMPLE_FLAGS 


# 256x256 (unconditional)
# MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond False --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
# python scripts/image_resample.py $MODEL_FLAGS --exp_name $EXP_NAME --model_path models/256x256_diffusion_uncond.pt $SAMPLE_FLAGS 

# 128x128
# MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --image_size 128 --learn_sigma True --noise_schedule linear --num_channels 256 --num_heads 4 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
# python scripts/classifier_sample.py $MODEL_FLAGS --classifier_scale 0.5 --classifier_path models/128x128_classifier.pt --model_path models/128x128_diffusion.pt $SAMPLE_FLAGS
